### ISSUE TITLE
All MineLP Textures need to be updated/redone

### ISSUE THREAD

**Issue by Sollace** [Love-and-Tolerance/Love-and-Tolerance#26]
Missing:
- [ ] new villager textures
- [ ] drowned pony
- [ ] ender stallion

1.16+
- [ ] Piglins
- [ ] Parasprites

**Comment by Venaf** [comment]
Skeletons need to have glow added.

**Comment by Sollace** [comment]
@VelvetRemedy Reminder that you've been assigned this issue

**Comment by PCelestia** [comment]
@Sollace since you said that this covers everything, I have decided to take those two lists and put them here.

ive seen an issue about minelp armor textures in L&T rendering as invalid, so might as well check those

confirmed needs fixing:
 - [ ] iron chestplate

confirmed doesn't need fixing:
 - [X] leather chestplate

I don't know yet:
 - [ ] leather helmet
 - [ ] leather leggings
 - [ ] leather boots
 - [ ] chainmail helmet
 - [ ] chainmail chestplate
 - [ ] chainmail leggings
 - [ ] chainmail boots
 - [ ] iron helmet
 - [ ] iron leggings
 - [ ] iron boots
 - [ ] diamond helmet
 - [ ] diamond chestplate
 - [ ] diamond leggings
 - [ ] diamond boots
 - [ ] gold helmet
 - [ ] gold chestplate
 - [ ] gold leggings
 - [ ] gold boots
 - [ ] turtle shell

eventually:
 - [ ] netherite helmet
 - [ ] netherite chestplate
 - [ ] netherite leggings
 - [ ] netherite boots


these are textures that aren't present in the pack right now. i don't know if we intend to add them, so I'm just going to list all of them here. if we arent going to add it, mark it as complete. and unmark it if we are adding it to the pack

entity:
 - [ ] enderman
 - [ ] illager
 - [X] pony (doesn't look like it)
 - [ ] zombie villager
 - [X] Alex pony
 - [X] seapony
 - [X] steve pony
 - [X] wandering trader
 - [X] witch pony

gui:
 - [X] pony (the only thing that's there

mob:
 - [X] noskin alex
 - [X] noskin steve
 - [X] noskin seapony

models:
 - [X] antlers
 - [X] muffin
 - [X] saddlebags
 - [X] stetson

all files in minelp armor folder are present in l&t

these files present in armor, but not in minelp 4.0.9-1.15.2 (might want to remove them)
 - [ ] chainmail_layer_1_pony
 - [ ] chainmail_layer_2_pony
 - [ ] diamond_layer_1_pony
 - [ ] diamond_layer_2_pony
 - [ ] gold_layer_1_pony
 - [ ] gold_layer_2_pony
 - [ ] iron_layer_1
 - [ ] iron_layer_1_pony
 - [ ] iron_layer_2
 - [ ] iron_layer_2_pony
 - [ ] iron_layer_inner
 - [ ] iron_layer_outer
 - [ ] leather_layer_1_overlay_pony
 - [ ] leather_layer_1_pony
 - [ ] leather_layer_2_overlay_pony
 - [ ] leather_layer_2_pony

took this list from minelp 4.0.9-1.15.2

**Comment by vayandas** [comment]
> Skeletons need to have glow added.

Has been fixed for both wither and regular skeleton

**Comment by SilkRose** [comment]
Moved to:
https://github.com/Love-and-Tolerance/MineLittlePony-Mod-Support/issues/1
